services:
  - type: web
    name: hydroserv-backend
    runtime: go
    plan: free
    rootDir: backend
    buildCommand: "cd backend && go build -o app ./cmd/api/main.go"
    startCommand: "cd backend && ./app"
    healthCheckPath: /ping
    autoDeploy: true
    envVars:
      - key: APP_PORT
        value: 10000
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: "https://project-3-5ss7.onrender.com"
      - key: JWT_EXPIRES_IN
        value: 720h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 8760h
      - key: SUPABASE_STORAGE_BUCKET
        value: hydraulic-reports
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: FCM_SERVICE_ACCOUNT_PATH
        value: firebase-service-account.json